### GET ALL BOOKS

GET http://localhost:5000/books HTTP/1.1

### GET AN BOOK 2
GET http://localhost:5000/books/643044de02ce8d1fd1af43db HTTP/1.1


### ADD A BOOK
POST http://localhost:5000/books HTTP/1.1
Content-Type: application/json

{
  "title": "War and Peace",
  "author": "Lew Tolstoj",
  "year": 1898
}

### DELETE A BOOK
DELETE http://localhost:5000/books/64304c33e9709332d1f3a074 HTTP/1.1

### UPDATE A BOOK
PUT http://localhost:5000/books/643044de02ce8d1fd1af43db HTTP/1.1
Content-Type: application/json

{
    "title": "updated book 3"
}
#######################################################################################
### GET A USER
GET http://localhost:5000/user/2 HTTP/1.1
